TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB 		    += devsri.db
DB_INSTALLS += $(TOP)/sriSup/devsri.proto
#=======================================
include $(TOP)/configure/RULES
